# Força o Quarkus a rodar na interface de rede externa da OCI
%prod.quarkus.http.host=0.0.0.0
%prod.quarkus.http.port=8080

# Token do bot do Telegram
# Se não encontrar a variável de ambiente, usa um token fictício válido para iniciar o contexto
telegram.bot.token=${TELEGRAM_BOT_TOKEN:123456:fallback-telegram-token}

# Configuração padrão de Produção (Workload Identity para a OCI)
# Busca da variável de ambiente GOOGLE_CONFIG_PATH. 
# Se não informada, usa o arquivo no diretório relativo de trabalho da aplicação (./google-workload-config.json)
google.config.path=${GOOGLE_CONFIG_PATH:google-workload-config.json}
google.calendar.id=${GOOGLE_CALENDAR_ID:primary}

# (%dev.) se aplica APENAS quando você roda localmente
%dev.google.config.path=/google-local-cred.json
%dev.google.calendar.id=${GOOGLE_CALENDAR_ID:primary}

# URL base da API de IA do Google
gemini.api.url=https://generativelanguage.googleapis.com/v1beta

# Chave de API do Gemini (usa um texto fictício como fallback em vez de string vazia)
gemini.api.key=${GEMINI_API_KEY:mock_gemini_api_key}

# Rest Client apontando para a URL base
quarkus.rest-client.gemini-api.url=https://generativelanguage.googleapis.com/v1beta

# Evita quebra de payload caso o Telegram envie campos extras no JSON
quarkus.jackson.fail-on-unknown-properties=false