# src/main/resources/application.properties
telegram.bot.token={TELEGRAM_BOT_TOKEN}

# Configuração padrão de Produção (Workload Identity para a OCI)
google.config.path=/google-workload-config.json
google.calendar.id=seu_id_de_producao@group.calendar.google.com

# (%dev.) se aplica APENAS quando você roda localmente
%dev.google.config.path=/google-local-cred.json
%dev.google.calendar.id={GOOGLE_CALENDAR_ID}

# URL base da API de IA do Google
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.api.key={GEMINI_API_KEY}
quarkus.rest-client.gemini-api.url=${gemini.api.url}

# Evita quebra de payload caso o Telegram envie campos extras no JSON
quarkus.jackson.fail-on-unknown-properties=false