# src/main/resources/application.properties
telegram.bot.token={TELEGRAM_BOT_TOKEN}

# URL base da API de IA do Google
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.api.key={GEMINI_API_KEY}
quarkus.rest-client.gemini-api.url=${gemini.api.url}

# Evita quebra de payload caso o Telegram envie campos extras no JSON
quarkus.jackson.fail-on-unknown-properties=false